import { useState, type ReactNode } from 'react'
import { Activity, BadgeCheck, BarChart3, BookOpenCheck, FlaskConical, Gauge } from 'lucide-react'
import type { BreakdownRow,Lang,SeriesPoint } from './types'

const compact=(value:number,lang:Lang)=>new Intl.NumberFormat(lang==='pt'?'pt-BR':'en-US',{notation:'compact',maximumFractionDigits:1}).format(Number.isFinite(value)?value:0)
const pct=(value:number)=>`${(100*(Number.isFinite(value)?value:0)).toFixed(1)}%`
const num=(row:Record<string,string|number>,key:string)=>Number(row[key]??0)
export function trendStats(rows:SeriesPoint[]){const values=rows.map(row=>Number(row.value)).filter(Number.isFinite);if(!values.length)return{mean:0,cv:0,first:0,last:0,change:0,points:0};const mean=values.reduce((s,v)=>s+v,0)/values.length,sd=Math.sqrt(values.reduce((s,v)=>s+(v-mean)**2,0)/values.length),first=values[0],last=values.at(-1)??0;return{mean,cv:mean?sd/mean:0,first,last,change:first?(last-first)/first:0,points:values.length}}
export function changeDrivers(rows:BreakdownRow[]){return rows.filter(row=>row.previous!==undefined).map(row=>({...row,change:row.value-(row.previous??0)})).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change))}
export function concentration(rows:BreakdownRow[],total:number){const ranked=[...rows].sort((a,b)=>b.value-a.value),shares=ranked.map(row=>total?row.value/total:0);return{leader:ranked[0],top3Share:shares.slice(0,3).reduce((s,v)=>s+v,0),hhi:shares.reduce((s,v)=>s+10_000*v*v,0)}}

function Stat({value,children,tone}:{value:string;children:ReactNode;tone?:'positive'|'negative'}){return <article><strong className={tone}>{value}</strong><span>{children}</span></article>}
function DriverList({rows,lang,inverse=true}:{rows:ReturnType<typeof changeDrivers>;lang:Lang;inverse?:boolean}){const shown=rows.slice(0,4),max=Math.max(...shown.map(row=>Math.abs(row.change)),1);return <div className="evidence-driver-list">{shown.map(row=>{const positive=inverse?row.change<=0:row.change>=0;return <div key={row.name}><span>{row.name}</span><i><b style={{width:`${100*Math.abs(row.change)/max}%`}}/></i><strong className={positive?'positive':'negative'}>{row.change>=0?'▲':'▼'} {compact(Math.abs(row.change),lang)}</strong></div>})}</div>}

type Lens=0|1|2|3|4
const copy:Record<string,{title:[string,string];tabs:[string,string][];questions:[string,string][]}>={
 service:{title:['Five lenses for service triage','Cinco lentes para triagem de serviço'],tabs:[['Signal','Sinal'],['Volume drivers','Drivers'],['Timeliness','Prazo'],['Concentration','Concentração'],['SLA scenario','Cenário SLA']],questions:[['Is variation above an attention limit?','A variação supera o limite de atenção?'],['Which products moved intake?','Quais produtos moveram a entrada?'],['How many exceptions sit behind the rate?','Quantas exceções existem por trás da taxa?'],['Is volume concentrated?','O volume está concentrado?'],['What if untimely responses decline?','E se os atrasos diminuírem?']]},
 issues:{title:['Five lenses for emerging issues','Cinco lentes para problemas emergentes'],tabs:[['Momentum','Momento'],['Issue drivers','Drivers'],['Persistence','Persistência'],['Concentration','Concentração'],['Triage scenario','Cenário']],questions:[['What is gaining operational relevance?','O que ganha relevância operacional?'],['Which issues changed most?','Quais problemas mais mudaram?'],['Is issue breadth stable?','A amplitude de problemas é estável?'],['Is attention concentrated?','A atenção está concentrada?'],['What if the leading issue declines?','E se o principal problema diminuir?']]},
 response:{title:['Five lenses for response performance','Cinco lentes para desempenho de resposta'],tabs:[['Timeliness','Prazo'],['Exception burden','Exceções'],['Company spread','Empresas'],['Rate stability','Estabilidade'],['SLA scenario','Cenário SLA']],questions:[['How timely is the operation?','Qual é o nível de resposta no prazo?'],['How many exceptions remain?','Quantas exceções permanecem?'],['How broad is the operating scope?','Qual é a abrangência operacional?'],['Is the timely rate stable?','A taxa no prazo é estável?'],['What if untimely responses decline?','E se reduzirmos atrasos?']]},
 narratives:{title:['Five lenses for narrative evidence','Cinco lentes para evidência narrativa'],tabs:[['Coverage','Cobertura'],['Topic mix','Mix de temas'],['Concentration','Concentração'],['Evidence gaps','Lacunas'],['Review scenario','Cenário de revisão']],questions:[['How much text evidence is available?','Quanto texto está disponível?'],['Which topics dominate narratives?','Quais temas dominam os relatos?'],['Does interpretation rely on few topics?','A interpretação depende de poucos temas?'],['How much evidence is missing?','Quanta evidência está ausente?'],['What if review coverage expands?','E se ampliarmos a revisão?']]},
 context:{title:['Five lenses for comparable context','Cinco lentes para contexto comparável'],tabs:[['Product scope','Produtos'],['Geography','Geografia'],['Company breadth','Empresas'],['Comparability','Comparabilidade'],['Minimum sample','Amostra mínima']],questions:[['Which products define the scope?','Quais produtos definem o recorte?'],['How broad is geography?','Qual é a abrangência geográfica?'],['How broad is company participation?','Qual é a participação de empresas?'],['Are comparisons like for like?','As comparações são equivalentes?'],['How many groups meet a minimum sample?','Quantos grupos atendem uma amostra mínima?']]},
 trust:{title:['Five lenses for evidence trust','Cinco lentes para confiança da evidência'],tabs:[['Coverage','Cobertura'],['Completeness','Completude'],['Boundaries','Limites'],['Reconciliation','Reconciliação'],['Readiness','Prontidão']],questions:[['What does the source cover?','O que a fonte cobre?'],['Did critical checks pass?','Os testes críticos passaram?'],['What cannot be concluded?','O que não pode ser concluído?'],['Do scoped totals reconcile?','Os totais do recorte reconciliam?'],['Can this evidence support triage?','A evidência sustenta triagem?']]}
}

function EvidenceLab({pageId,values,previous,trend,breakdown,detail,lang}:{pageId:string;values:Record<string,number>;previous:Record<string,number>;trend:SeriesPoint[];breakdown:BreakdownRow[];detail:Record<string,string|number>[];lang:Lang}){
 const[lens,setLens]=useState<Lens>(0),[scenario,setScenario]=useState(25),[threshold,setThreshold]=useState(100)
 const c=copy[pageId]??copy.trust,stats=trendStats(trend),drivers=changeDrivers(breakdown),total=pageId==='trust'?(values.rows||0):(values.complaints||0),conc=concentration(breakdown,total),complaints=values.complaints||values.rows||0,timely=values.timely||0,late=values.untimely??complaints*(1-timely),change=previous.complaints?(complaints-previous.complaints)/previous.complaints:0,checks=detail.filter(row=>'status'in row),failed=checks.filter(row=>String(row.status)!=='Passed').length
 const icons=[Activity,BarChart3,BadgeCheck,Gauge,pageId==='trust'?BookOpenCheck:FlaskConical]
 let content:ReactNode
 if(pageId==='service'){
  const mean=stats.mean,limit=mean+2*(stats.cv*mean),anomalies=trend.filter(row=>row.value>limit).length,avoided=late*scenario/100
  const views=[<><Stat value={String(anomalies)} tone={anomalies?'negative':undefined}>{lang==='pt'?'dias acima de média + 2 DP':'days above mean + 2 SD'}</Stat><Stat value={compact(mean,lang)}>{lang==='pt'?'média diária':'daily mean'}</Stat><Stat value={compact(limit,lang)}>{lang==='pt'?'limite descritivo':'descriptive limit'}</Stat></>,<DriverList rows={drivers} lang={lang}/>,<><Stat value={pct(timely)} tone={timely>=.95?'positive':'negative'}>{lang==='pt'?'respostas no prazo':'timely responses'}</Stat><Stat value={compact(late,lang)} tone={late?'negative':undefined}>{lang==='pt'?'fora do prazo estimadas':'estimated untimely'}</Stat><Stat value={compact(values.companies||0,lang)}>{lang==='pt'?'empresas no recorte':'companies in scope'}</Stat></>,<><Stat value={pct(conc.top3Share)}>Top 3</Stat><Stat value={Math.round(conc.hhi).toLocaleString(lang==='pt'?'pt-BR':'en-US')}>HHI</Stat><Stat value={conc.leader?.name??'—'}>{lang==='pt'?'produto líder':'leading product'}</Stat></>,<><label><span>{lang==='pt'?'Redução de atrasos':'Untimely reduction'} <b>{scenario}%</b></span><input type="range" min="5" max="60" value={scenario} onChange={e=>setScenario(Number(e.target.value))}/></label><Stat value={compact(avoided,lang)}>{lang==='pt'?'atrasos potencialmente evitados':'potential exceptions avoided'}</Stat><Stat value={compact(late-avoided,lang)}>{lang==='pt'?'atrasos remanescentes':'remaining exceptions'}</Stat></>]
  content=views[lens]
 }else if(pageId==='issues'){
  const reduced=(conc.leader?.value??0)*scenario/100
  const views=[<><Stat value={pct(change)} tone={change<=0?'positive':'negative'}>{lang==='pt'?'volume versus período anterior':'volume versus prior period'}</Stat><Stat value={compact(values.issues||0,lang)}>{lang==='pt'?'categorias ativas':'active issue categories'}</Stat><Stat value={pct(values.top_issue_share||0)}>{lang==='pt'?'participação do principal problema':'leading issue share'}</Stat></>,<DriverList rows={drivers} lang={lang}/>,<><Stat value={pct(stats.cv)}>{lang==='pt'?'variação da quantidade de temas':'issue-count variability'}</Stat><Stat value={compact(stats.mean,lang)}>{lang==='pt'?'média diária de temas':'daily issue breadth'}</Stat><Stat value={String(stats.points)}>{lang==='pt'?'dias observados':'observed days'}</Stat></>,<><Stat value={pct(conc.top3Share)}>Top 3</Stat><Stat value={Math.round(conc.hhi).toLocaleString(lang==='pt'?'pt-BR':'en-US')}>HHI</Stat><Stat value={conc.leader?.name??'—'}>{lang==='pt'?'problema líder':'leading issue'}</Stat></>,<><label><span>{lang==='pt'?'Redução do líder':'Leader reduction'} <b>{scenario}%</b></span><input type="range" min="5" max="60" value={scenario} onChange={e=>setScenario(Number(e.target.value))}/></label><Stat value={compact(reduced,lang)}>{lang==='pt'?'casos alvo':'target cases'}</Stat><Stat value={compact(complaints-reduced,lang)}>{lang==='pt'?'volume total ajustado':'adjusted total volume'}</Stat><Stat value="Sensitivity">{lang==='pt'?'não é previsão causal':'not a causal forecast'}</Stat></>]
  content=views[lens]
 }else if(pageId==='response'){
  const avoided=late*scenario/100
  const views=[<><Stat value={pct(timely)} tone={timely>=.95?'positive':'negative'}>{lang==='pt'?'respostas no prazo':'timely responses'}</Stat><Stat value={compact(late,lang)} tone={late?'negative':undefined}>{lang==='pt'?'fora do prazo':'untimely responses'}</Stat><Stat value={compact(complaints,lang)}>{lang==='pt'?'respostas avaliadas':'responses assessed'}</Stat></>,<><Stat value={pct(complaints?late/complaints:0)} tone={late?'negative':undefined}>{lang==='pt'?'carga de exceções':'exception burden'}</Stat><Stat value={compact(late,lang)}>{lang==='pt'?'casos para revisão':'cases for review'}</Stat><Stat value={compact(values.responses||0,lang)}>{lang==='pt'?'resultados de resposta':'response outcomes'}</Stat></>,<><Stat value={compact(values.companies||0,lang)}>{lang==='pt'?'empresas representadas':'companies represented'}</Stat><Stat value={String(detail.length)}>{lang==='pt'?'contextos exibidos':'displayed contexts'}</Stat><Stat value={conc.leader?.name??'—'}>{lang==='pt'?'resultado dominante':'dominant outcome'}</Stat></>,<><Stat value={`${stats.change>=0?'▲':'▼'} ${pct(Math.abs(stats.change))}`} tone={stats.change>=0?'positive':'negative'}>{lang==='pt'?'primeiro ao último dia':'first to last day'}</Stat><Stat value={pct(stats.cv)}>{lang==='pt'?'variabilidade da taxa':'rate variability'}</Stat><Stat value={`${stats.mean.toFixed(1)}%`}>{lang==='pt'?'média diária no prazo':'daily timely average'}</Stat></>,<><label><span>{lang==='pt'?'Redução de atrasos':'Untimely reduction'} <b>{scenario}%</b></span><input type="range" min="5" max="60" value={scenario} onChange={e=>setScenario(Number(e.target.value))}/></label><Stat value={compact(avoided,lang)}>{lang==='pt'?'exceções potencialmente evitadas':'potential exceptions avoided'}</Stat><Stat value={pct(complaints?(late-avoided)/complaints:0)}>{lang==='pt'?'carga remanescente':'remaining burden'}</Stat></>]
  content=views[lens]
 }else if(pageId==='narratives'){
  const coverage=values.narratives||0,missing=values.missing_narratives||0,reviewed=missing*scenario/100
  const views=[<><Stat value={pct(coverage)} tone={coverage>=.8?'positive':'negative'}>{lang==='pt'?'cobertura narrativa':'narrative coverage'}</Stat><Stat value={compact(values.narrative_count||0,lang)}>{lang==='pt'?'relatos disponíveis':'available narratives'}</Stat><Stat value={compact(complaints,lang)}>{lang==='pt'?'reclamações no escopo':'complaints in scope'}</Stat></>,<><Stat value={conc.leader?.name??'—'}>{lang==='pt'?'tópico líder':'leading topic'}</Stat><Stat value={compact(values.topics||0,lang)}>{lang==='pt'?'tópicos explicáveis':'explainable topics'}</Stat><Stat value={String(breakdown.length)}>{lang==='pt'?'tópicos exibidos':'displayed topics'}</Stat></>,<><Stat value={pct(conc.top3Share)}>Top 3</Stat><Stat value={Math.round(conc.hhi).toLocaleString(lang==='pt'?'pt-BR':'en-US')}>HHI</Stat><Stat value="Descriptive">{lang==='pt'?'não representa causalidade':'not causal evidence'}</Stat></>,<><Stat value={compact(missing,lang)} tone={missing?'negative':undefined}>{lang==='pt'?'relatos ausentes':'missing narratives'}</Stat><Stat value={pct(1-coverage)}>{lang==='pt'?'gap de evidência':'evidence gap'}</Stat></>,<><label><span>{lang==='pt'?'Revisar lacunas':'Review missing'} <b>{scenario}%</b></span><input type="range" min="5" max="60" value={scenario} onChange={e=>setScenario(Number(e.target.value))}/></label><Stat value={compact(reviewed,lang)}>{lang==='pt'?'casos adicionais revisados':'additional cases reviewed'}</Stat><Stat value={pct(complaints?(values.narrative_count+reviewed)/complaints:0)}>{lang==='pt'?'cobertura após cenário':'coverage after scenario'}</Stat></>]
  content=views[lens]
 }else if(pageId==='context'){
  const eligible=detail.filter(row=>num(row,'complaints')>=threshold).length
  const views=[<><Stat value={compact(values.products||0,lang)}>{lang==='pt'?'produtos representados':'products represented'}</Stat><Stat value={compact(complaints,lang)}>{lang==='pt'?'reclamações no recorte':'complaints in scope'}</Stat><Stat value="No denominator">{lang==='pt'?'não é taxa de qualidade':'not a quality rate'}</Stat></>,<><Stat value={compact(values.states||0,lang)}>{lang==='pt'?'jurisdições representadas':'jurisdictions represented'}</Stat><Stat value={conc.leader?.name??'—'}>{lang==='pt'?'jurisdição com maior volume':'highest-volume jurisdiction'}</Stat><Stat value={pct(conc.top3Share)}>Top 3</Stat></>,<><Stat value={compact(values.companies||0,lang)}>{lang==='pt'?'empresas representadas':'companies represented'}</Stat><Stat value={String(detail.length)}>{lang==='pt'?'grupos exibidos':'displayed groups'}</Stat></>,<><Stat value="Like for like">{lang==='pt'?'mesmo produto, período e amostra':'same product, period and sample'}</Stat><Stat value="Required">{lang==='pt'?'denominador externo para taxas':'external denominator for rates'}</Stat><Stat value="No ranking">{lang==='pt'?'qualidade geral não inferida':'overall quality not inferred'}</Stat></>,<><label><span>{lang==='pt'?'Amostra mínima':'Minimum sample'} <b>{threshold}</b></span><input type="range" min="10" max="1000" step="10" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><Stat value={String(eligible)}>{lang==='pt'?'grupos elegíveis exibidos':'displayed eligible groups'}</Stat><Stat value={String(detail.length-eligible)}>{lang==='pt'?'grupos abaixo do corte':'groups below threshold'}</Stat></>]
  content=views[lens]
 }else{
  const views=[<><Stat value={compact(values.rows||0,lang)}>{lang==='pt'?'linhas no recorte':'rows in scope'}</Stat><Stat value={compact(values.days||0,lang)}>{lang==='pt'?'dias cobertos':'days covered'}</Stat><Stat value={compact(values.products||0,lang)}>{lang==='pt'?'produtos cobertos':'products covered'}</Stat></>,<><Stat value={String(checks.length-failed)} tone={failed?'negative':'positive'}>{lang==='pt'?'testes aprovados':'checks passed'}</Stat><Stat value={String(failed)} tone={failed?'negative':undefined}>{lang==='pt'?'testes para revisar':'checks to review'}</Stat></>,<><Stat value="Complaint record">{lang==='pt'?'grão da fonte':'source grain'}</Stat><Stat value="No exposure">{lang==='pt'?'sem base de clientes':'no customer denominator'}</Stat><Stat value="No causality">{lang==='pt'?'triagem, não prova':'triage, not proof'}</Stat></>,<><Stat value={compact(values.rows||0,lang)}>{lang==='pt'?'linhas recalculadas':'recalculated rows'}</Stat><Stat value={String(detail.length)}>{lang==='pt'?'testes publicados':'published checks'}</Stat><Stat value="Scoped">{lang==='pt'?'consulta no navegador':'browser query'}</Stat></>,<><Stat value={failed===0&&values.rows>0?(lang==='pt'?'Qualificada':'Qualified'):(lang==='pt'?'Revisar':'Review')} tone={failed?'negative':'positive'}>{lang==='pt'?'prontidão para triagem':'triage readiness'}</Stat><Stat value="Human review">{lang==='pt'?'necessária antes de ação':'required before action'}</Stat></>]
  content=views[lens]
 }
 return <section className="evidence-lab"><div className="evidence-lab-head"><div><span>{lang==='pt'?'LABORATÓRIO DA PÁGINA · MÉTODOS TRANSPARENTES':'PAGE LAB · TRANSPARENT METHODS'}</span><h2>{c.title[lang==='pt'?1:0]}</h2></div><div role="tablist">{c.tabs.map((tab,index)=>{const Icon=icons[index];return <button role="tab" aria-selected={lens===index} className={lens===index?'active':''} onClick={()=>setLens(index as Lens)} key={tab[0]}><Icon/>{tab[lang==='pt'?1:0]}</button>})}</div></div><div className="evidence-lab-body"><div className="evidence-copy"><b>{c.questions[lens][lang==='pt'?1:0]}</b><p>{lang==='pt'?'Calculado no recorte; volume de reclamações não é taxa de qualidade.':'Calculated within scope; complaint volume is not a quality rate.'}</p></div>{content}</div></section>
}

export function PageInsight({pageId,values,previous,trend,breakdown,detail,lang}:{pageId:string;values:Record<string,number>;previous:Record<string,number>;trend:SeriesPoint[];breakdown:BreakdownRow[];detail:Record<string,string|number>[];lang:Lang}){return <EvidenceLab pageId={pageId} values={values} previous={previous} trend={trend} breakdown={breakdown} detail={detail} lang={lang}/>}
