import ReactEChartsCore from 'echarts-for-react/lib/core'
import * as echarts from 'echarts/core'
import { LineChart } from 'echarts/charts'
import { GridComponent,MarkLineComponent,TooltipComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { ShieldAlert } from 'lucide-react'
import type { Lang,SeriesPoint } from './types'
echarts.use([LineChart,GridComponent,MarkLineComponent,TooltipComponent,CanvasRenderer])
export function IssueControlChart({data,lang}:{data:SeriesPoint[];lang:Lang}){const mean=data.reduce((s,r)=>s+r.value,0)/(data.length||1),sd=Math.sqrt(data.reduce((s,r)=>s+(r.value-mean)**2,0)/(data.length||1)),limit=mean+2*sd,anomalies=data.filter(r=>r.value>limit).length,option={animationDuration:350,grid:{left:12,right:20,top:20,bottom:18,containLabel:true},tooltip:{trigger:'axis'},xAxis:{type:'category',data:data.map(r=>r.label),axisLabel:{color:'#697588'}},yAxis:{type:'value',splitLine:{lineStyle:{color:'#eceff3'}}},series:[{type:'line',data:data.map(r=>({value:r.value,itemStyle:{color:r.value>limit?'#b63649':'#284d7b'}})),showSymbol:false,lineStyle:{color:'#284d7b',width:2},areaStyle:{color:'rgba(40,77,123,.07)'},markLine:{symbol:'none',label:{formatter:lang==='pt'?'Limite de atenção':'Attention limit'},lineStyle:{color:'#b63649',type:'dashed'},data:[{yAxis:limit}]}}]};return <section className="control"><div className="control-copy"><ShieldAlert/><span>{lang==='pt'?'INOVAÇÃO · DETECÇÃO DE SINAL':'INNOVATION · SIGNAL DETECTION'}</span><h2>{lang==='pt'?'Variação normal ou pico investigável?':'Normal variation or investigable spike?'}</h2><p>{lang==='pt'?`${anomalies} dias ultrapassam o limite estatístico de atenção. Isso é triagem, não prova de causa.`:`${anomalies} days exceed the statistical attention limit. This is triage, not proof of cause.`}</p></div><div className="chart-viewport"><ReactEChartsCore echarts={echarts} option={option} style={{height:190,width:'100%'}}/></div></section>}
