import type { BreakdownRow,SeriesPoint } from './types'
export type FilterState={channel:string;device:string;country:string}
export type MartResult={current:Record<string,number>;previous:Record<string,number>;trend:SeriesPoint[];breakdown:BreakdownRow[];detail:Record<string,string|number>[];context:{topDriver:string;topShare:number;anomalies:number}}
let connectionPromise:Promise<import('@duckdb/duckdb-wasm').AsyncDuckDBConnection>|undefined
const literal=(value:string)=>`'${value.replaceAll("'","''")}'`
async function connection(){if(!connectionPromise)connectionPromise=(async()=>{const d=await import('@duckdb/duckdb-wasm'),b=await d.selectBundle(d.getJsDelivrBundles()),workerUrl=URL.createObjectURL(new Blob([`importScripts("${b.mainWorker!}");`],{type:'text/javascript'})),db=new d.AsyncDuckDB(new d.ConsoleLogger(),new Worker(workerUrl));await db.instantiate(b.mainModule,b.pthreadWorker);await db.registerFileURL('complaints.parquet',new URL('./data/mart_complaints.parquet',window.location.href).href,d.DuckDBDataProtocol.HTTP,false);return db.connect()})();return connectionPromise}
const records=(table:{toArray:()=>Record<string,unknown>[]})=>table.toArray().map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,typeof v==='bigint'?Number(v):v]))) as Record<string,string|number>[]
let queryQueue:Promise<void>=Promise.resolve()
export function queryMart(filters:FilterState,pageId:string):Promise<MartResult>{const result=queryQueue.then(()=>runQuery(filters,pageId));queryQueue=result.then(()=>undefined,()=>undefined);return result}
async function runQuery(filters:FilterState,pageId:string):Promise<MartResult>{const con=await connection(),clauses=[filters.channel&&`product=${literal(filters.channel)}`,filters.device&&`company=${literal(filters.device)}`,filters.country&&`state=${literal(filters.country)}`].filter(Boolean),where=clauses.length?`where ${clauses.join(' and ')}`:''
 const metrics=async(period:'current'|'previous')=>{const op=period==='current'?'>=':'<',t=await con.query(`with base as(select * from read_parquet('complaints.parquet') ${where}),bounds as(select min(received_date) lo,max(received_date) hi from base),scoped as(select b.* from base b,bounds where received_date ${op} lo+((hi-lo)/2)::integer) select count(*)::double complaints,avg(timely)::double timely,count(distinct company)::double companies,avg(has_narrative)::double narratives,avg(monetary_relief)::double relief,count(distinct product)::double products,count(distinct received_date)::double coverage_days from scoped`),r=t.get(0) as Record<string,unknown>;return Object.fromEntries(Object.entries(r).map(([k,v])=>[k,Number(v??0)])) as Record<string,number>}
 const current=await metrics('current'),previous=await metrics('previous'),trendTable=await con.query(`select strftime(received_date,'%b %d') period_label,count(*)::double metric_value from read_parquet('complaints.parquet') ${where} group by received_date order by received_date`),dimension=pageId==='response'?'company':pageId==='context'?'state':'product',breakdownTable=await con.query(`select ${dimension} as driver_name,count(*)::double as driver_value from read_parquet('complaints.parquet') ${where} group by 1 order by driver_value desc limit 12`),detailTable=await con.query(`select ${dimension} as context,count(*)::double as complaints,round(100*avg(timely),1)::double as timely_pct,round(100*avg(has_narrative),1)::double as narrative_pct,count(distinct company)::double as companies from read_parquet('complaints.parquet') ${where} group by 1 order by complaints desc limit 25`)
 const trend=trendTable.toArray().map(r=>({label:String(r.period_label),value:Number(r.metric_value)})),mean=trend.reduce((s,r)=>s+r.value,0)/(trend.length||1),sd=Math.sqrt(trend.reduce((s,r)=>s+(r.value-mean)**2,0)/(trend.length||1)),breakdown=records(breakdownTable).map(r=>({name:String(r.driver_name??'Unknown'),value:Number(r.driver_value??0)})),total=breakdown.reduce((s,r)=>s+r.value,0)
 return{current,previous,trend,breakdown,detail:records(detailTable),context:{topDriver:breakdown[0]?.name??'N/A',topShare:total?breakdown[0].value/total:0,anomalies:trend.filter(r=>r.value>mean+2*sd).length}}
}
