import type { BreakdownRow,SeriesPoint } from './types'
export type FilterState={channel:string;device:string;country:string;period:'1'|'3'|'all'}
export type DrillItem={dimension:'product'|'company'|'state'|'issue'|'topic'|'company_response';value:string}
export type MartResult={current:Record<string,number>;previous:Record<string,number>;trend:SeriesPoint[];breakdown:BreakdownRow[];detail:Record<string,string|number>[];context:{topDriver:string;topShare:number;anomalies:number;dimension:string;canDrill:boolean}}
let connectionPromise:Promise<import('@duckdb/duckdb-wasm').AsyncDuckDBConnection>|undefined
const literal=(value:string)=>`'${value.replaceAll("'","''")}'`
async function connection(){if(!connectionPromise)connectionPromise=(async()=>{const d=await import('@duckdb/duckdb-wasm'),b=await d.selectBundle(d.getJsDelivrBundles()),workerUrl=URL.createObjectURL(new Blob([`importScripts("${b.mainWorker!}");`],{type:'text/javascript'})),db=new d.AsyncDuckDB(new d.ConsoleLogger(),new Worker(workerUrl));await db.instantiate(b.mainModule,b.pthreadWorker);await db.registerFileURL('complaints.parquet',new URL('./data/mart_complaints.parquet',window.location.href).href,d.DuckDBDataProtocol.HTTP,false);return db.connect()})();return connectionPromise}
const records=(table:{toArray:()=>Record<string,unknown>[]})=>table.toArray().map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,typeof v==='bigint'?Number(v):v]))) as Record<string,string|number>[]
let queryQueue:Promise<void>=Promise.resolve()
export function queryMart(filters:FilterState,pageId:string,drillPath:DrillItem[]=[]):Promise<MartResult>{const result=queryQueue.then(()=>runQuery(filters,pageId,drillPath));queryQueue=result.then(()=>undefined,()=>undefined);return result}
async function runQuery(filters:FilterState,pageId:string,drillPath:DrillItem[]):Promise<MartResult>{
 const con=await connection(),clauses=[filters.channel&&`product=${literal(filters.channel)}`,filters.device&&`company=${literal(filters.device)}`,filters.country&&`state=${literal(filters.country)}`,...drillPath.map(item=>`${item.dimension}=${literal(item.value)}`)].filter(Boolean),where=clauses.length?`where ${clauses.join(' and ')}`:'',days=filters.period==='all'?0:Number(filters.period),range=`with base as(select * from read_parquet('complaints.parquet') ${where}),bounds as(select min(received_date) lo,max(received_date) hi from base),ranges as(select ${days?`hi-${days-1}`:'lo'} current_start,hi current_end,${days?`hi-${days*2-1}`:'NULL::DATE'} previous_start,${days?`hi-${days}`:'NULL::DATE'} previous_end from bounds)`
 const metricSelect:Record<string,string>={
  service:`count(*)::double complaints,avg(timely)::double timely,count(distinct company)::double companies,avg(has_narrative)::double narratives,avg(monetary_relief)::double relief`,
  issues:`count(*)::double complaints,count(distinct issue)::double issues,(select max(c)::double/nullif((select count(*) from scoped),0) from (select count(*) c from scoped group by issue)) top_issue_share,avg(timely)::double timely`,
  response:`count(*)::double complaints,avg(timely)::double timely,count(*) filter(where timely=0)::double untimely,avg(monetary_relief)::double relief,count(distinct company)::double companies,count(distinct company_response)::double responses`,
  narratives:`count(*)::double complaints,count(*) filter(where has_narrative=1)::double narrative_count,avg(has_narrative)::double narratives,count(distinct topic)::double topics,count(*) filter(where has_narrative=0)::double missing_narratives`,
  context:`count(*)::double complaints,count(distinct state)::double states,count(distinct product)::double products,count(distinct company)::double companies`,
  trust:`count(*)::double "rows",count(distinct product)::double products,count(distinct company)::double companies,count(distinct received_date)::double "days"`
 }
 const metrics=async(period:'current'|'previous')=>{const t=await con.query(`${range},scoped as(select b.* from base b,ranges where received_date between ${period}_start and ${period}_end) select ${metricSelect[pageId]??metricSelect.service} from scoped`),r=t.get(0) as Record<string,unknown>;return Object.fromEntries(Object.entries(r).map(([k,v])=>[k,Number(v??0)])) as Record<string,number>}
 const trendMetric:Record<string,string>={service:'count(*)',issues:'count(distinct issue)',response:'100*avg(timely)',narratives:'count(*) filter(where has_narrative=1)',context:'count(distinct state)',trust:'100*avg(case when product is not null and company is not null and complaint_id is not null then 1 else 0 end)'}
 const current=await metrics('current'),previous=await metrics('previous'),trendTable=await con.query(`${range} select strftime(received_date,'%b %d') period_label,(${trendMetric[pageId]??trendMetric.service})::double metric_value from base,ranges where received_date between current_start and current_end group by received_date order by received_date`),hierarchies:Record<string,Array<DrillItem['dimension']>>={service:['product','issue','company'],issues:['issue','product','company'],response:['company_response','company','product'],narratives:['topic','issue','product'],context:['state','product','company'],trust:['product','state','company']},hierarchy=hierarchies[pageId]??hierarchies.service,dimension=hierarchy[Math.min(drillPath.length,hierarchy.length-1)],breakdownTable=await con.query(`${range} select coalesce(${dimension},'Unknown') as driver_name,count(*) filter(where received_date between current_start and current_end)::double as driver_value,count(*) filter(where received_date between previous_start and previous_end)::double as previous_value from base,ranges group by 1 order by driver_value desc limit 12`)
 const detailSql:Record<string,string>={
  service:`select coalesce(${dimension},'Unknown') context,count(*)::double complaints,round(100*avg(timely),1)::double timely_pct,round(100*avg(has_narrative),1)::double narrative_pct,count(distinct company)::double companies from scoped group by 1 order by complaints desc limit 25`,
  issues:`select coalesce(${dimension},'Unknown') context,count(*)::double complaints,round(100*count(*)/sum(count(*)) over(),1)::double share_pct,round(100*avg(timely),1)::double timely_pct,count(distinct product)::double products from scoped group by 1 order by complaints desc limit 25`,
  response:`select coalesce(${dimension},'Unknown') context,count(*)::double complaints,round(100*avg(timely),1)::double timely_pct,round(100*avg(monetary_relief),1)::double relief_pct,count(distinct product)::double products from scoped group by 1 order by complaints desc limit 25`,
  narratives:`select coalesce(${dimension},'Unknown') context,count(*) filter(where has_narrative=1)::double narratives,round(100*avg(has_narrative),1)::double coverage_pct,count(distinct issue)::double issues,count(distinct product)::double products from scoped group by 1 order by narratives desc limit 25`,
  context:`select coalesce(${dimension},'Unknown') context,count(*)::double complaints,count(distinct company)::double companies,count(distinct product)::double products,round(100*avg(timely),1)::double timely_pct from scoped group by 1 order by complaints desc limit 25`
 }
 const detailTable=pageId==='trust'?await con.query(`${range},scoped as(select b.* from base b,ranges where received_date between current_start and current_end) select 'Unique complaint IDs' check_name,case when count(*)=count(distinct complaint_id) then 'Passed' else 'Failed' end status,count(*)::varchar observed from scoped union all select 'Critical fields complete',case when count(*) filter(where product is null or company is null or received_date is null)=0 then 'Passed' else 'Review' end,(count(*) filter(where product is null or company is null or received_date is null))::varchar from scoped union all select 'Valid response flag',case when count(*) filter(where timely not in (0,1))=0 then 'Passed' else 'Failed' end,(count(*) filter(where timely not in (0,1)))::varchar from scoped`) : await con.query(`${range},scoped as(select b.* from base b,ranges where received_date between current_start and current_end) ${detailSql[pageId]??detailSql.service}`)
 const trend=trendTable.toArray().map(r=>({label:String(r.period_label),value:Number(r.metric_value)})),mean=trend.reduce((s,r)=>s+r.value,0)/(trend.length||1),sd=Math.sqrt(trend.reduce((s,r)=>s+(r.value-mean)**2,0)/(trend.length||1)),breakdown=records(breakdownTable).map(r=>({name:String(r.driver_name??'Unknown'),value:Number(r.driver_value??0),previous:filters.period==='all'?undefined:Number(r.previous_value??0)})),total=pageId==='trust'?(current.rows||0):(current.complaints||0)
 return{current,previous,trend,breakdown,detail:records(detailTable),context:{topDriver:breakdown[0]?.name??'N/A',topShare:total?breakdown[0].value/total:0,anomalies:trend.filter(r=>r.value>mean+2*sd).length,dimension,canDrill:drillPath.length<hierarchy.length-1}}
}
